tab_title_separator: " - "

favicon: https://cdn.zengjunyin.com/favicon.ico

apple_touch_icon: https://cdn.zengjunyin.com/avatar.png

code:
  highlight:
    highlightjs:
      style: "Routeros"
      style_dark: "Lioshi"

fun_features:
  anchorjs:
    placement: right
    visible: always
    icon: "#"
  progressbar:
    color: "#eea2a4"

dark_mode:
  default: auto

color:
  body_bg_color: "#f7f8fa"
  body_bg_color_dark: "#151718"

  navbar_bg_color: "#fff"
  navbar_bg_color_dark: "#232222"

  navbar_text_color: "#373e4a"
  navbar_text_color_dark: "#d8d8d8"

  subtitle_color: "#373e4a"
  subtitle_color_dark: "#d8d8d8"

  text_color: "#373e4a"
  text_color_dark: "#d8d8d8"

  sec_text_color: "#979898"
  sec_text_color_dark: "#979898"

  board_color: "#fff"
  board_color_dark: "#232222"

  post_text_color: "#373e4a"
  post_text_color_dark: "#d8d8d8"

  post_heading_color: "#373e4a"
  post_heading_color_dark: "#d8d8d8"

  post_link_color: "#eea2a4"
  post_link_color_dark: "#f1939c"

  link_hover_color: "#f07c82"
  link_hover_color_dark: "#f07c82"

  link_hover_bg_color: "rgba(0,0,0,0.1)"
  link_hover_bg_color_dark: "rgba(0,0,0,0.1)"

  line_color: "#979898"
  line_color_dark: "#979898"

  scrollbar_color: "#eea2a4"
  scrollbar_color_dark: "#eea2a4"

  scrollbar_hover_color: "#f07c82"
  scrollbar_hover_color_dark: "#f07c82"

  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"

  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"

font:
  font_size: 15px
  font_family: Noto Serif SC, sans-serif;
  letter_spacing: 0.06em

custom_css: css/hexo.css

lazyload:
  loading_img: https://article.biliimg.com/bfs/article/b7bb2a197ce8caa47bcea068be3794372972d455.gif@800w_400h_1c.webp
  onlypost: true

iconfont: //at.alicdn.com/t/c/font_3048099_c8qyj3uwdpd.css

navbar:
  menu:
    - { key: "归档", link: "/archives/", icon: "iconfont icon-archive" }
    - { key: "分类", link: "/categories/", icon: "iconfont icon-category" }
    - { key: "说说", link: "/daily/", icon: "iconfont icon-love" }
    - { key: "友链", link: "/links/", icon: "iconfont icon-link" }
    - { key: "关于", link: "https://www.zengjunyin.com", icon: "iconfont icon-user" }

footer:
  content: '
    <a target="_blank" href="https://hexo.io" title="框架 Hexo"><img src="https://cdn.zengjunyin.com/label-1.svg"></a>
    <a target="_blank" href="https://hexo.fluid-dev.com/docs/" title="主题 Fluid"><img src="https://cdn.zengjunyin.com/label-2.svg"></a>
  '

  beian:
    enable: false
    icp_text: 闽ICP备2021019269号

index:
  auto_excerpt:
    enable: false
  post_meta:
    date: true
    category: true
    tag: false
  post_sticky:
    enable: true
    icon: "iconfont icon-iconfonticonfonti2copy"

post:
  meta:
    author:
      enable: true
    wordcount:
      enable: false
    min2read:
      enable: false
  copyright:
    enable: true
    license: 'BY-NC'
  image_zoom:
    enable: true
    img_url_replace: ['re:(@).*$', '']
  comments:
    enable: true
    type: twikoo

twikoo:
  envId: https://twikoo.zengjunyin.com
  path: window.location.pathname

about:
  title: "关于"
  subtitle: "可有可无的自白墙"
  avatar: https://cdn.zengjunyin.com/avatar.png
  name: "胤"
  intro: "所念皆星河"
  icons:
    - { class: "iconfont icon-HTML-fill", link: "https://www.zengjunyin.com", tip: "Home" }
    - { class: "iconfont icon-github-fill", link: "https://github.com/GinMiraing", tip: "GitHub" }
    - { class: "iconfont icon-mail_fill", link: "mailto:zengjunyin@foxmail.com", tip: "Mail" }

links:
  title: "友情链接"
  subtitle: "一些可爱的朋友们"
  items:
    - {
      title: "山川行貉",
      intro: "快让我在雪地上撒点儿野.",
      link: "https://blog.scxho.cn",
      avatar: "https://scxho.cn/1.png"
    }
    - {
      title: "Vian",
      intro: "想要的都拥有，得不到的都释怀...",
      link: "https://vian.top",
      avatar: "https://vian.top/avatar.ico"
    }
    - {
      title: "山茶花舍",
      intro: "吕楪在记录自己的生活",
      link: "https://irithys.com",
      avatar: "https://irithys.com/img/avatar_hubbf77efc6dc5667fd8ba4d90170d6399_48198_300x0_resize_q75_h2_box_2.webp"
    }
    - {
      title: "小予",
      intro: "愿山野浓雾都有路灯风...",
      link: "https://yvu.cc",
      avatar: "https://cravatar.cn/avatar/9581bec449e7289c8b0a77f949d5bbea?s=100&d=mm&r=g"
    }
    - {
      title: "频率",
      intro: "风卷过的起点",
      link: "https://pinlyu.com",
      avatar: "https://pinlyu.com/resources/img/avatar.webp"
    }
    - {
      title: "林林杂语",
      intro: "林林在无病呻吟",
      link: "https://www.xiaozonglin.cn",
      avatar: "https://thirdqq.qlogo.cn/g?b=sdk&k=BprL2nDXwddtThAKbAFBtw&kti=Y3tljAAAAAE&s=140&t=1644206293"
    }
  onerror_avatar: https://article.biliimg.com/bfs/article/fe739a158cc128f70f780eb5fa96f388b81d478f.png@.webp

static_prefix:
  twikoo: https://cdn.staticfile.org/twikoo/1.6.16/